{{- if eq .Values.secobserveSecret.existingSecret "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secobserve.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secobserve.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  password: {{ default (randAlphaNum 16) .Values.secobserveSecret.adminPassword | b64enc }}
  admin: {{ .Values.secobserveSecret.adminUser | default "admin" | b64enc }}
  django_secret_key: {{ randAlphaNum 64 | b64enc }}
  field_encryption_key: {{ randBytes 32  | b64enc }}
{{- end }}
