---
# Source: secobserve/charts/postgresql/templates/primary/networkpolicy.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: release-name-postgresql
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.6.0
    helm.sh/chart: postgresql-16.7.27
    app.kubernetes.io/component: primary
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/component: primary
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    - ports:
        - port: 5432
---
# Source: secobserve/charts/postgresql/templates/primary/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: release-name-postgresql
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.6.0
    helm.sh/chart: postgresql-16.7.27
    app.kubernetes.io/component: primary
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/component: primary
---
# Source: secobserve/charts/postgresql/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-postgresql
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.6.0
    helm.sh/chart: postgresql-16.7.27
automountServiceAccountToken: false
---
# Source: secobserve/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-postgresql
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.6.0
    helm.sh/chart: postgresql-16.7.27
type: Opaque
data:
  postgres-password: "UXM5Wm9tUW9aNw=="
  password: "djBEV044TXVQMA=="
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
---
# Source: secobserve/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "secobserve-secret"
  namespace: "default"
  labels:
    helm.sh/chart: secobserve-1.0.14
    com.secobserve.tenant: secobserve
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.46.1"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  password: 'NHh5TWNWOVVNQmZwZkQ1SA=='
  admin: 'YWRtaW4='
  django_secret_key: 'cmZKZHBSTElWSTF0TUFqNEdCM3RibVhVVk83OFhrWTA4dkJLODAxUTVIenpBQWJUcUo1WG5ZSGZWT3FwdGNONg=='
  field_encryption_key: 'aWpLUGdwaWlYNTRsYUlJVEJYS0FIMUU4aWFPWTFtNmtkelBxNW1zMUZOUmtuRGYxQ2hmMkRpREhPU0RQenZGcQ=='
---
# Source: secobserve/charts/postgresql/templates/primary/svc-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-postgresql-hl
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.6.0
    helm.sh/chart: postgresql-16.7.27
    app.kubernetes.io/component: primary
  annotations:
spec:
  type: ClusterIP
  clusterIP: None
  # We want all pods in the StatefulSet to have their addresses published for
  # the sake of the other Postgresql pods even before they're ready, since they
  # have to be able to talk to each other in order to become ready.
  publishNotReadyAddresses: true
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: primary
---
# Source: secobserve/charts/postgresql/templates/primary/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-postgresql
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.6.0
    helm.sh/chart: postgresql-16.7.27
    app.kubernetes.io/component: primary
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
      nodePort: null
  selector:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: primary
---
# Source: secobserve/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "secobserve-svc"
  namespace: "default"
  labels:
    helm.sh/chart: secobserve-1.0.14
    com.secobserve.tenant: secobserve
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.46.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: frontend-http
      port: 3000
      targetPort: frontend-http
      protocol: TCP
    - name: backend-http
      port: 5000
      targetPort: backend-http
      protocol: TCP
  selector:
    com.secobserve.tenant: secobserve
    app.kubernetes.io/instance: release-name
---
# Source: secobserve/charts/postgresql/templates/primary/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: release-name-postgresql
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.6.0
    helm.sh/chart: postgresql-16.7.27
    app.kubernetes.io/component: primary
spec:
  replicas: 1
  serviceName: release-name-postgresql-hl
  updateStrategy:
    rollingUpdate: {}
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/component: primary
  template:
    metadata:
      name: release-name-postgresql
      labels:
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: postgresql
        app.kubernetes.io/version: 17.6.0
        helm.sh/chart: postgresql-16.7.27
        app.kubernetes.io/component: primary
    spec:
      serviceAccountName: release-name-postgresql
      
      automountServiceAccountToken: false
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: release-name
                    app.kubernetes.io/name: postgresql
                    app.kubernetes.io/component: primary
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
        supplementalGroups: []
        sysctls: []
      hostNetwork: false
      hostIPC: false
      containers:
        - name: postgresql
          image: docker.io/bitnamilegacy/postgresql:17.6.0-debian-12-r4
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: POSTGRESQL_PORT_NUMBER
              value: "5432"
            - name: POSTGRESQL_VOLUME_DIR
              value: "/bitnami/postgresql"
            - name: PGDATA
              value: "/bitnami/postgresql/data"
            # Authentication
            - name: POSTGRES_USER
              value: "secobserve"
            - name: POSTGRES_PASSWORD_FILE
              value: /opt/bitnami/postgresql/secrets/password
            - name: POSTGRES_POSTGRES_PASSWORD_FILE
              value: /opt/bitnami/postgresql/secrets/postgres-password
            - name: POSTGRES_DATABASE
              value: "secobserve"
            # LDAP
            - name: POSTGRESQL_ENABLE_LDAP
              value: "no"
            # TLS
            - name: POSTGRESQL_ENABLE_TLS
              value: "no"
            # Audit
            - name: POSTGRESQL_LOG_HOSTNAME
              value: "false"
            - name: POSTGRESQL_LOG_CONNECTIONS
              value: "false"
            - name: POSTGRESQL_LOG_DISCONNECTIONS
              value: "false"
            - name: POSTGRESQL_PGAUDIT_LOG_CATALOG
              value: "off"
            # Others
            - name: POSTGRESQL_CLIENT_MIN_MESSAGES
              value: "error"
            - name: POSTGRESQL_SHARED_PRELOAD_LIBRARIES
              value: "pgaudit"
          ports:
            - name: tcp-postgresql
              containerPort: 5432
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "secobserve" -d "dbname=secobserve" -h 127.0.0.1 -p 5432
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            exec:
              command:
                - /bin/sh
                - -c
                - -e
                - |
                  exec pg_isready -U "secobserve" -d "dbname=secobserve" -h 127.0.0.1 -p 5432
                  [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
          resources:
            limits:
              cpu: 150m
              ephemeral-storage: 2Gi
              memory: 192Mi
            requests:
              cpu: 100m
              ephemeral-storage: 50Mi
              memory: 128Mi
          volumeMounts:
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp-dir
            - name: empty-dir
              mountPath: /opt/bitnami/postgresql/conf
              subPath: app-conf-dir
            - name: empty-dir
              mountPath: /opt/bitnami/postgresql/tmp
              subPath: app-tmp-dir
            - name: postgresql-password
              mountPath: /opt/bitnami/postgresql/secrets/
            - name: dshm
              mountPath: /dev/shm
            - name: data
              mountPath: /bitnami/postgresql
      volumes:
        - name: empty-dir
          emptyDir: {}
        - name: postgresql-password
          secret:
            secretName: release-name-postgresql
        - name: dshm
          emptyDir:
            medium: Memory
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
---
# Source: secobserve/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: secobserve-sts
  namespace: "default"
  labels:
    helm.sh/chart: secobserve-1.0.14
    com.secobserve.tenant: secobserve
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.46.1"
    app.kubernetes.io/managed-by: Helm
spec:
  serviceName: secobserve-svc
  replicas: 1
  selector:
    matchLabels:
      com.secobserve.tenant: secobserve
      app.kubernetes.io/instance: release-name
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        com.secobserve.tenant: secobserve
        app.kubernetes.io/instance: release-name
    spec:
      initContainers:
        - name: dbchecker
          image: "busybox:latest"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
          command:
            - sh
            - -c
            - |
              echo 'Waiting for Database to become ready...'

              until printf "." && nc -z -w 2 release-name-postgresql 5432; do
                  sleep 2;
              done;

              echo 'Database OK âœ“'
          resources:
            limits:
              cpu: 20m
              memory: 32Mi
            requests:
              cpu: 20m
              memory: 32Mi
      containers:
        - name: frontend
          image: "ghcr.io/secobserve/secobserve-frontend:1.46.1"
          imagePullPolicy: IfNotPresent
          env:
            - name: API_BASE_URL
              value: https://secobserve.dev/api
            - name: OIDC_ENABLED
              value: "false"
            - name: OIDC_AUTHORITY
              value: https://oidc.secobserve.dev
            - name: OIDC_CLIENT_ID
              value: secobserve
            - name: OIDC_REDIRECT_URI
              value: https://secobserve.dev/
            - name: OIDC_POST_LOGOUT_REDIRECT_URI
              value: https://secobserve.dev/
          ports:
            - name: frontend-http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 300
            timeoutSeconds: 5
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            timeoutSeconds: 5
            failureThreshold: 12
          resources:
            limits:
              cpu: 500m
              memory: 1000Mi
            requests:
              cpu: 500m
              memory: 1000Mi
          volumeMounts:

        - name: backend
          image: "ghcr.io/secobserve/secobserve-backend:1.46.1"
          imagePullPolicy: IfNotPresent
          env:
            - name: ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: "secobserve-secret"
                  key: password
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "secobserve-secret"
                  key: password
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: "secobserve-secret"
                  key: django_secret_key
            - name: FIELD_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: "secobserve-secret"
                  key: field_encryption_key
            - name: ADMIN_EMAIL
              value: admin@admin.com
            - name: DATABASE_ENGINE
              value: django.db.backends.postgresql
            - name: DATABASE_HOST
              value: secobserve-postgresql
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_DB
              value: secobserve
            - name: DATABASE_USER
              value: secobserve
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: secobserve-postgresql
            - name: ALLOWED_HOSTS
              value: secobserve.dev
            - name: CORS_ALLOWED_ORIGINS
              value: https://secobserve.dev
            - name: OIDC_AUTHORITY
              value: https://oidc.secobserve.dev
            - name: OIDC_CLIENT_ID
              value: secobserve
            - name: OIDC_USERNAME
              value: preferred_username
            - name: OIDC_FIRST_NAME
              value: given_name
            - name: OIDC_LAST_NAME
              value: family_name
            - name: OIDC_FULL_NAME
              value: preferred_username
            - name: OIDC_EMAIL
              value: email
            - name: OIDC_GROUPS
              value: groups
          ports:
            - name: backend-http
              containerPort: 5000
          livenessProbe:
            httpGet:
              path: /api/status/health/
              port: 5000
            initialDelaySeconds: 300
            timeoutSeconds: 5
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /api/status/health/
              port: 5000
            initialDelaySeconds: 20
            timeoutSeconds: 5
            failureThreshold: 12
          resources:
            limits:
              cpu: 1000m
              memory: 1500Mi
            requests:
              cpu: 1000m
              memory: 1500Mi
          volumeMounts:

      volumes:
---
# Source: secobserve/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secobserve-ing
  namespace: "default"
  labels:
    helm.sh/chart: secobserve-1.0.14
    com.secobserve.tenant: secobserve
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.46.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: secobserve.dev
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: secobserve-svc
                port:
                  name: backend-http
          - path: /django-static/
            pathType: Prefix
            backend:
              service:
                name: secobserve-svc
                port:
                  name: backend-http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: secobserve-svc
                port:
                  name: frontend-http
