name: Check frontend

on:
  push:
    paths-ignore:
      - charts/**
  pull_request:
    paths-ignore:
      - charts/**

permissions: read-all

jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 24

      - name: Install dependencies
        working-directory: ./frontend
        run: |
          npm ci

      - name: Prettier
        working-directory: ./frontend
        run: |
          npx prettier -c src

      - name: ESLint
        working-directory: ./frontend
        run: |
          npx eslint src

  end_to_end_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: End-to-end tests
        working-directory: .
        run: |
          cd end_to_end_tests
          npm install
          cd ..
          docker compose -f docker-compose-playwright.yml build
          docker compose -f docker-compose-playwright.yml up --abort-on-container-exit --exit-code-from playwright

  check_code_sonarqube_frontend:
    if: github.repository == 'SecObserve/SecObserve' && (github.ref == 'refs/heads/dev' || github.event_name == 'pull_request')
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0  
      - 
        name: Run SonarQube scan for frontend
        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9 # v7.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}
        with:
          projectBaseDir: frontend
